// <auto-generated />
namespace _036_MoviesMvcWissen.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class MoviesV02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MoviesV02));
        
        string IMigrationMetadata.Id
        {
            get { return "202002141352263_MoviesV02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
